= Food Truck Fan features

== Favorites ❤️

Scan QR code to Favorite the Food Truck in our App. See also xref:product/food-truck-setup-process.adoc[Setup Process] and xref:product/integrations.adoc[Integrations].

* If the person has the app installed, open the Food Truck profile and favorite the Food Truck automatically
* If the person does not have the app installed, open the food truck in a Temporary App without installing the app first. The instant app will let them save the food truck to local cache without logging in, so they can receive notifications when the food truck comes back. The instant app will have a button at the bottom for "Favorite". When they click the button, they will see a pop-up dialog telling them that they will be notified when the food truck arrives in their location.
* Under the "Favorite" button, there will be a "Sign up" button. When they click, offer to install the app immediately, or open the app store page

== Temporary App for info 📲

Android Instant App and iOS App Clips can provide an app-like experience without installation.

=== Android Instant App

Summary and use cases for Instant Apps.

=== iOS App Clips

Summary and use cases for App Clips.

== Experimental ideas

Augmented Reality 🤳: Scan QR code to see an AR menu.

